format = """
[╭╼╾ $username ╼╾ $time$python$golang ╼╾](bold blue) $status $cmd_duration
[╞╾פּ ](bold blue)$directory$git_branch$git_commit$git_state$git_status$hg_branch
[╰╼╾](bold blue)$character"""

[directory]
truncation_length = 2
truncation_symbol = " "
style = "cyan"
read_only = " "
disabled = false

[username]
style_user = "bold blue"
style_root = "red"
show_always = true
format = "[$user]($style)"
disabled = false

[hostname]
ssh_only = false
format = "[$hostname]($style)"
trim_at = "."
style = "blue"
disabled = true

[character]
success_symbol = "[](bold blue)"
error_symbol = "[](bold blue)"
disabled = false

[cmd_duration]
min_time = 420
show_milliseconds = false
format = "[$duration](cyan)"
disabled = false

[git_branch]
truncation_length = 12
style = "bold cyan"
truncation_symbol = "..."
disabled = false

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "
tag_disabled = false
only_detached = true
disabled = false

[git_status]
format = '([ $conflicted$staged$untracked$ahead_behind$renamed$deleted$stashed$modified]($style))'
conflicted = "[ ](bold #e278ad)"
stashed = "[ ${count} ](bold birght-black)"
modified = "[ ${count} ](bold cyan)"
staged = '[ ${count} ](bold yellow)'
untracked = '[ ${count} ](bold #e2d078)'
renamed = "[ ${count} ](bold purple)"
deleted = "[ ${count} ](bold red)"
ahead = "[⯭ ${count} ](bold green)"
diverged = '[ [${ahead_count} ](bold green) [${behind_count} ](bold red)](bold purple)'
behind = '[⯯ ${count} ](bold red)'
style = "bold blue"
disabled = false

[memory_usage]
format = "[${ram}]($style)"
threshold = -1
symbol = ""
style = "dimmed blue"
disabled = true

[time]
disabled = false
format = '[$time]($style)'
time_format = "%R"
style = "blue"

[status]
format = '[$symbol$status]($style) '
style = "bold red"
symbol = " "
disabled = false

[python]
format = '[${symbol}${pyenv_prefix}(${version})( \($virtualenv\))]($style)'
symbol = " ╼╾  "
style = "blue"

[golang]
format = "[$symbol($version)]($style)"
symbol = " ╼╾ ﳑ "
style = "blue"
