# ============================================================================
# 🧰 setup  {{{
add_newline = true
scan_timeout = 10
continuation_prompt = """[    ⋯  ](blu_2)"""
palette = 'vagari' # palette definition must be last
# }}}
# ============================================================================

format = """
[╭╼╾ $sudo$username ╼╾ ${custom.date1} ${custom.date2}$python$rust$lua ╼╾ $hostname](blu_2)
[╞╾](blu_2)$directory$git_branch$git_commit$git_state$git_status
[╰╼╾ $character](blu_2)
"""

right_format = """[$status $cmd_duration╼╾ $time ╼╾╯](blu_2)"""


[character]
success_symbol = "[](blu_2)"
error_symbol = "[](blu_2)"
vimcmd_symbol = "[](blu_2)"

[directory]
style = "bold blu_3"
truncation_symbol = "⽙"
read_only = " "
home_symbol = "⾕"

[username]
style_user = "blu_2"
style_root = "rby_2"
format = "[⼈$user]($style)"
show_always = true

[hostname]
style = "blu_2"
ssh_only = false
format = "[$hostname ⾥]($style)"
trim_at = "."

[cmd_duration]
min_time = 420
show_milliseconds = false
format = "[$duration ](grn_3)"
disabled = false

[git_branch]
truncation_length = 12
style = "orn_2"
symbol = "⽀"
truncation_symbol = "..."
format = "[$symbol$branch(:$remote_branch)]($style)"

[git_status]
style = "orn_3"
format = '[ $ahead_behind$conflicted$renamed$staged$modified$untracked$stashed$deleted]($style)'
conflicted = "[ ](pnk_3)"
stashed = "[ ${count} ](slt_2)"
modified = "[🞊 ${count} ](sky_2)"
staged = '[ ${count} ](orn_3)'
untracked = '[ ${count} ](sun_3)'
renamed = "[ ${count} ](prp_3)"
ahead = "[⯭${count} ](grn_3)"
diverged = '[ [${ahead_count} ](grn_3) [${behind_count} ](rby_3)](prp_3)'
behind = '[⯯${count} ](rby_3)'
deleted = "[ ${count} ](rby_3)"

[time]
format = '[$time]($style)'
time_format = "時%R"
style = "pnk_4"
disabled = false

[status]
style = "blu_2"
success_symbol = "[](grn_3)"
not_executable_symbol = "[🕱 $common_meaning](slt_2)"
not_found_symbol = "[ $common_meaning](rby_3)"
sigint_symbol = "[ ABORT](blu_2)"
signal_symbol = "[🗲 $int](sun_3)"
symbol = "[ $int $common_meaning](rby_3)"
recognize_signal_code = true
pipestatus_format = """[⽣ $pipestatus ⽍]($style)"""
pipestatus_separator = "[ » ]($style)"
map_symbol = true
pipestatus = true
format = '[$symbol]($style)'
disabled = false

[sudo]
format = "[󰌆 ](orn_3)"
disabled = false

[python]
format = '[[ ╼╾](blu_2) $symbol ${pyenv_prefix}(${version})( \($virtualenv\))]($style)'
symbol = ""
style = "grn_3"

[rust]
format = "[ ╼╾](blu_2) [$symbol ($version )]($style)"
symbol = ""
style = "orn_3"

[lua]
symbol = ""
style = "fg"
format = "[[ ╼╾](blu_2) $symbol ($version)]($style)"

[custom.date1]
style = "prp_2"
description = "simple date module, day only"
command = "date '+%a'"
symbol = "⽇"
format = "[$symbol($output)]($style)"
when = true

[custom.date2]
style = "prp_1"
description = "simple date module, weekday only"
command = "date '+%d'"
symbol = "⽉"
format = "[$symbol($output)]($style)"
when = true

[palettes.vagari]

# ☯️  Bounds {{{

bg = '#222536' # HSL 231 23 17 CR: 1.00
fg = '#aeb9f8' # HSL 231 84 83 CR: 8.00

drk_0 = '#1e2133' # HSL: 231 26 16 CR: 1.05
drk_1 = '#181b2c' # HSL: 231 29 13 CR: 1.12
drk_2 = '#131626' # HSL: 231 33 11 CR: 1.18
drk_3 = '#0d0f1b' # HSL: 231 35 08 CR: 1.26

blk_0 = '#1d1d21' # HSL: 240 06 12 CR: 1.11
blk_1 = '#16161a' # HSL: 240 08 09 CR: 1.19
blk_2 = '#101014' # HSL: 240 11 07 CR: 1.25
blk_3 = '#0b0b0f' # HSL: 240 15 05 CR: 1.30

brt_0 = '#b6c0f7' # HSL: 231 80 84 CR: 8.56
brt_1 = '#bec6f8' # HSL: 231 81 86 CR: 9.11
brt_2 = '#cad1fb' # HSL: 231 86 89 CR: 10.12
brt_3 = '#d1d8ff' # HSL: 231 100 91 CR: 11.21

wht_0 = '#c9c9e2' # HSL: 240 30 84 CR: 9.33
wht_1 = '#d3d3ed' # HSL: 240 42 88 CR: 10.41
wht_2 = '#ddddf6' # HSL: 240 58 92 CR: 11.36
wht_3 = '#e9e9fb' # HSL: 240 69 95 CR: 12.63

# }}}

# 📡 Communicative {{{

blu_0 = '#4a6be3' # HSL: 227 72 59 CR: 3.24
blu_1 = '#6380ec' # HSL: 227 78 66 CR: 4.20
blu_2 = '#7492ef' # HSL: 225 79 70 CR: 5.12
blu_3 = '#8aa4f3' # HSL: 225 81 75 CR: 6.26
blu_4 = '#9db2f4' # HSL: 226 80 79 CR: 7.29

orn_0 = '#e56b2c' # HSL: 20 78 54 CR: 4.66
orn_1 = '#ea834b' # HSL: 21 79 61 CR: 5.66
orn_2 = '#eb905d' # HSL: 22 78 64 CR: 6.26
orn_3 = '#f2a170' # HSL: 23 83 70 CR: 7.29
orn_4 = '#f8b486' # HSL: 24 89 75 CR: 8.56

grn_0 = '#5b9542' # HSL: 102 39 42 CR: 4.20
grn_1 = '#73ad5a' # HSL: 102 34 52 CR: 5.66
grn_2 = '#85ba6d' # HSL: 101 36 58 CR: 6.67
grn_3 = '#95cb79' # HSL: 100 44 64 CR: 8.00
grn_4 = '#9fd883' # HSL: 100 52 68 CR: 9.11

prp_0 = '#7f61cd' # HSL: 257 52 59 CR: 3.24
prp_1 = '#9376d8' # HSL: 258 56 65 CR: 4.20
prp_2 = '#a188df' # HSL: 257 58 70 CR: 5.12
prp_3 = '#b29ae8' # HSL: 258 63 76 CR: 6.26
prp_4 = '#bdaaeb' # HSL: 258 62 79 CR: 7.29

# }}}

# 🚥 Signaling {{{

emr_0 = '#2d9a43' # HSL: 133 55 39 CR: 4.20
emr_1 = '#48a95b' # HSL: 132 40 47 CR: 5.12
emr_2 = '#5aba6d' # HSL: 132 41 54 CR: 6.26
emr_3 = '#5fc976' # HSL: 133 50 58 CR: 7.29
emr_4 = '#76d78b' # HSL: 133 55 65 CR: 8.56

rby_0 = '#f34658' # HSL: 354 88 61 CR: 4.20
rby_1 = '#f36978' # HSL: 353 85 68 CR: 5.12
rby_2 = '#f07a88' # HSL: 353 80 71 CR: 5.66
rby_3 = '#f08898' # HSL: 351 78 74 CR: 6.26
rby_4 = '#f29ca9' # HSL: 351 87 78 CR: 7.29

sun_0 = '#f3a338' # HSL: 34 89 59 CR: 7.29
sun_1 = '#f5b855' # HSL: 37 89 65 CR: 8.56
sun_2 = '#f5c069' # HSL: 37 87 69 CR: 9.11
sun_3 = '#f4ce88' # HSL: 39 83 75 CR: 10.12
sun_4 = '#f5d599' # HSL: 39 82 78 CR: 10.72

sky_0 = '#369fd7' # HSL: 201 67 53 CR: 5.12
sky_1 = '#54b0e2' # HSL: 201 71 61 CR: 6.26
sky_2 = '#6bbdec' # HSL: 202 77 67 CR: 7.29
sky_3 = '#7cc5ef' # HSL: 202 78 71 CR: 8.00
sky_4 = '#90d1f5' # HSL: 201 83 76 CR: 9.11

cy2_0 = '#2bb198' # HSL: 169 61 43 CR: 5.66
cy2_1 = '#30c9b0' # HSL: 170 62 49 CR: 7.29
cy2_2 = '#38d2ba' # HSL: 171 63 52 CR: 8.00
cy2_3 = '#50dec8' # HSL: 171 68 59 CR: 9.11
cy2_4 = '#75e6d5' # HSL: 171 69 68 CR: 10.12

pnk_0 = '#d15da6' # HSL: 322 56 59 CR: 4.20
pnk_1 = '#e36cb8' # HSL: 322 68 66 CR: 5.12
pnk_2 = '#ea76c0' # HSL: 322 73 69 CR: 5.66
pnk_3 = '#e887c3' # HSL: 323 68 72 CR: 6.26
pnk_4 = '#ed9acd' # HSL: 323 70 77 CR: 7.29

# }}}

# ⚗️  Muted {{{

his_0 = '#824141' # HSL: 0 33 38 CR: 2.00
his_1 = '#b15e5b' # HSL: 1 35 53 CR: 3.33
his_2 = '#c67a79' # HSL: 1 40 63 CR: 4.66
his_3 = '#d09490' # HSL: 4 41 69 CR: 6.00

glu_0 = '#3b557c' # HSL: 217 29 36 CR: 2.00
glu_1 = '#5b77a4' # HSL: 217 29 50 CR: 3.33
glu_2 = '#7690b9' # HSL: 217 32 59 CR: 4.66
glu_3 = '#90a4c7' # HSL: 218 32 67 CR: 6.00

asn_0 = '#6f447a' # HSL: 288 28 37 CR: 2.00
asn_1 = '#9961a7' # HSL: 288 28 52 CR: 3.33
asn_2 = '#af7dba' # HSL: 289 31 61 CR: 4.66
asn_3 = '#c193cd' # HSL: 288 37 69 CR: 6.00

pro_0 = '#505831' # HSL: 72 28 27 CR: 2.00
pro_1 = '#717b45' # HSL: 71 28 38 CR: 3.33
pro_2 = '#8a945b' # HSL: 71 24 47 CR: 4.66
pro_3 = '#9ea876' # HSL: 72 22 56 CR: 6.00

tyr_0 = '#375c47' # HSL: 146 25 29 CR: 2.00
tyr_1 = '#4b8163' # HSL: 147 26 40 CR: 3.33
tyr_2 = '#5a9c78' # HSL: 148 27 48 CR: 4.66
tyr_3 = '#72b08e' # HSL: 147 28 57 CR: 6.00

# }}}

# 👽 greys {{{

gry_0 = '#373945' # HSL: 231 11 24 CR: 1.32
gry_1 = '#3f414f' # HSL: 233 11 28 CR: 1.50
gry_2 = '#4f5163' # HSL: 234 11 35 CR: 1.94
gry_3 = '#5f6278' # HSL: 233 12 42 CR: 2.52
gry_4 = '#6d7089' # HSL: 235 11 49 CR: 3.12
gry_5 = '#7f8199' # HSL: 235 11 55 CR: 3.97

slt_0 = '#343852' # HSL: 232 22 26 CR: 1.32
slt_1 = '#3c4162' # HSL: 232 24 31 CR: 1.53
slt_2 = '#484e75' # HSL: 232 24 37 CR: 1.89
slt_3 = '#585f8d' # HSL: 232 23 45 CR: 2.47
slt_4 = '#686ea1' # HSL: 234 23 52 CR: 3.12
slt_5 = '#7b7fb0' # HSL: 235 25 59 CR: 3.97

glc_0 = '#252841' # HSL: 234 27 20 CR: 1.05
glc_1 = '#282b48' # HSL: 234 29 22 CR: 1.10
glc_2 = '#30345a' # HSL: 234 30 27 CR: 1.27
glc_3 = '#3f4578' # HSL: 234 31 36 CR: 1.68
glc_4 = '#4e5492' # HSL: 235 30 44 CR: 2.16
glc_5 = '#5a61aa' # HSL: 235 32 51 CR: 2.68

rst_0 = '#493531' # HSL: 10 20 24 CR: 1.32
rst_1 = '#563e39' # HSL: 10 20 28 CR: 1.54
rst_2 = '#694b44' # HSL: 11 21 34 CR: 1.94
rst_3 = '#805a52' # HSL: 10 22 41 CR: 2.52
rst_4 = '#92675d' # HSL: 11 22 47 CR: 3.11
rst_5 = '#a3786d' # HSL: 12 23 53 CR: 3.97

plm_0 = '#453445' # HSL: 300 14 24 CR: 1.32
plm_1 = '#523c52' # HSL: 300 14 28 CR: 1.53
plm_2 = '#634a64' # HSL: 298 15 34 CR: 1.96
plm_3 = '#765a77' # HSL: 298 14 41 CR: 2.52
plm_4 = '#876888' # HSL: 298 13 47 CR: 3.15
plm_5 = '#977998' # HSL: 298 13 54 CR: 3.97

olv_0 = '#383a39' # HSL: 150 2 22 CR: 1.32
olv_1 = '#414342' # HSL: 150 2 26 CR: 1.51
olv_2 = '#505251' # HSL: 150 1 32 CR: 1.92
olv_3 = '#5f6361' # HSL: 150 2 38 CR: 2.48
olv_4 = '#6e7270' # HSL: 150 1 45 CR: 3.10
olv_5 = '#818382' # HSL: 150 1 51 CR: 3.97

# }}}
